config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :projects do
    resource :project_interview, only: [:show, :update], path: :interview
    resource :project_questionnaire, only: [:show, :update], path: :questionnaire
    resources :project_templates, path: :templates do
      get :preview
    end

    resources :people, only: [:index, :create, :show, :update] do
      member do
        put :accept
        put :reject
      end

      collection do
        post :search
        delete :clear
      end
    end
  end

  resources :events

  resource :settings, only: [:show, :update] do
    resources :settings_templates, path: :templates
  end

  resources :word_relations

end

app/models/person.rb
class Person
  include Mongoid::Document
  extend EnumerateIt

  class Status < EnumerateIt::Base
    associate_values :new, :accepted, :rejected
  end

  before_save :fix_links

  field :name, type: String

  field :moikrug_link, type: String
  field :moikrug_profile, type: Hash

  field :facebook_link, type: String
  field :facebook_profile, type: Hash

  field :skills, type: String, default: ""
  field :experience, type: Array, default: -> { Array.new }

  field :email, type: String
  field :phone, type: String
  field :skype, type: String
  field :linkedin_link, type: String
  field :github_link, type: String
  field :stackoverflow_link, type: String
  field :facebook_link, type: String
  field :vk_link, type: String
  field :twitter_link, type: String
  field :googleplus_link, type: String
  field :resume_link, type: String

  field :status, type: String, default: :new

  scope :of, -> (user) { where(owner: user) }
  scope :accepted, -> { where(status: Status::ACCEPTED) }

  belongs_to :owner, class_name: "User", inverse_of: :candidates
  belongs_to :project

  has_enumeration_for :status, with: Status, create_helpers: true

  def fix_links
    self.facebook_link = URI.decode(facebook_link) if facebook_link
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  include Projectable

  helper_method :person, :persons, :last_query

  def index
  end

  def create
    create_person permitted[:name]
    render action: :index
  end

  def show
    render layout: -> { 'layouts/application' }
  end

  def update
    person.update_attributes(permitted)
    redirect_to project_person_path
  end

  def search
    project.search_queries << query
    project.save!

    digger = Digger.new query, start: page

    digger.call do |result|
      person = Person.of(current_user).where(name: result.name, project: project)

      unless person.exists?
        moikrug = Moikrug::ProfileFetcher.new(link: result.moikrug_link).call || {}
        facebook = {} # Faceboo::ProfileFetcher.new(link: result.facebook_link).call || {}
        person = create_person result.name, moikrug: moikrug, facebook: facebook
      end
    end

    project.update_attributes stats: { moikrug_last_query: digger.moikrug_query,
                                       pages_processed: page }

    render action: :index
  end

  def clear
    Person.of(current_user).delete
    render action: :index
  end

  def accept
    person.accepted!
    person.save!
    render action: :index
  end

  def reject
    person.rejected!
    person.save!
    render action: :index
  end

  def persons
    @persons ||= Person.of(current_user)
                       .where(project: project)
                       .in(status: [:new, :accepted])
                       .order(created_at: 1)
  end

  def person
    @person ||= Person.of(current_user).find(params[:id]) if params[:id]
  end

  private

  def create_person name, options = Hash.new
    Person::Creator.new(name, options.merge(project: project,
                                            user: current_user)).call
  end

  def query
    @query ||= SearchQuery.new search_params
  end

  def last_query
    project.search_queries.last || SearchQuery.new
  end

  def page
    params[:more].present? ? (params[:page].to_i || 1) : 1
  end

  def search_params
    search_params = params.require(:search_query).permit(:specializations, :city, :period, :contender)
    search_params[:specializations] = search_params[:specializations].split(",").map(&:strip)
    search_params[:city] = "Москва" unless search_params[:city].present?
    search_params[:period] = 2 unless search_params[:period].present?
    search_params
  end

  def permitted
    params.require(:person).permit(:name,
                                   :email,
                                   :phone,
                                   :skype,
                                   :moikrug_link,
                                   :linkedin_link,
                                   :github_link,
                                   :stackoverflow_link,
                                   :facebook_link,
                                   :vk_link,
                                   :twitter_link,
                                   :googleplus_link,
                                   :resume_link)
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def active_tab
    :people
  end

  def userpic_src person
    if person.moikrug_profile && person.moikrug_profile[:userpic]
      person.moikrug_profile[:userpic]
    else
      'http://nilcolor.moikrug.ru/images/blank_photo/portrait.png'
    end
  end

  def moikrug_name person
    return unless person.moikrug_profile.present?
    person.moikrug_profile[:nick]
  end

  def moikrug_url person
    person.moikrug_link
  end

  def facebook_name person
    return unless person.facebook_link.present?
    /^.*facebook\.com\/(?:people\/)?([^\/]+).*$/.match(person.facebook_link)[1]
  end

  def facebook_url person
  end

  def contact_link url, text, label
    if text.present?
      text = text.gsub(/http[s]?:\/\//, '')
      link_tag = "<a href='#{url}' target='_blank'>#{text}</a>"
    else
      link_tag = "<small><i class='nodata'>пока неизвестен</i></small>"
    end

    html = <<-HTML
      <div class="row">
        <div class="small-1 column"><strong>#{label}</strong></div>
        <div class="small-10 column">
          #{link_tag}
        </div>
      </div>
    HTML

    raw html
  end

  def email_link person
    contact_link "mailto:#{person.email}", person.email, icon(:at)
  end

  def phone_link person
    contact_link "tel:#{person.phone}", person.phone, icon(:phone)
  end

  def skype_link person
    contact_link "skype:#{person.skype}", person.skype, icon(:skype)
  end

  def moikrug_link person
    contact_link moikrug_url(person), moikrug_name(person), "MK"
  end

  def linkedin_link person
    contact_link person.linkedin_link, person.linkedin_link, icon(:linkedin)
  end

  def github_link person
    contact_link person.github_link, person.github_link, icon(:github)
  end

  def stackoverflow_link person
    contact_link person.stackoverflow_link, person.stackoverflow_link, icon('stack-overflow')
  end

  def vk_link person
    contact_link person.vk_link, person.vk_link, icon(:vk)
  end

  def twitter_link person
    contact_link person.twitter_link, person.twitter_link, icon(:twitter)
  end

  def googleplus_link person
    contact_link person.googleplus_link, person.googleplus_link, icon('google-plus')
  end

  def facebook_link person
    contact_link person.facebook_link, facebook_name(person), icon(:facebook)
  end

  def resume_link person
    contact_link person.resume_link, person.resume_link, icon('file-o')
  end
end

app/views/people/_contacts.html.slim
.row
  fieldset
    legend Поговорить
    .small-4.column
      = field_row icon(:at) do
        = f.text_field :email
    .small-4.column
      = field_row icon(:phone) do
        = f.text_field :phone
    .small-4.column
      = field_row icon(:skype) do
        = f.text_field :skype
.row
  fieldset
    legend Про работу
    .small-6.column
      = field_row 'MK' do
          = f.text_field :moikrug_link
    .small-6.column
      = field_row icon(:linkedin) do
        = f.text_field :linkedin_link
    .small-6.column
      = field_row icon(:github) do
        = f.text_field :github_link
    .small-6.column
      = field_row icon('stack-overflow') do
        = f.text_field :stackoverflow_link
.row
  fieldset
    legend Социалочки
    .small-6.column
      = field_row icon(:facebook) do
        = f.text_field :facebook_link
    .small-6.column
      = field_row icon(:vk) do
        = f.text_field :vk_link
    .small-6.column
      = field_row icon(:twitter) do
        = f.text_field :twitter_link
    .small-6.column
      = field_row icon('google-plus') do
        = f.text_field :googleplus_link

.row
  fieldset
    legend Резюме
    .small-12.column
      = field_row icon('file-o') do
        = f.text_field :resume_link, placeholder: "ссылка на файл"

app/views/people/_experience.html.slim
.row
  .small-12.column
    - (person.experience || []).each do |item|
      h5
        = "#{item[:title]} "
        small = item[:company]
      p = raw(item[:duties])

app/views/people/_person.html.slim
.reveal-modal data-reveal='' id="show-person-#{person.id}"
  = link_to project_person_path(id: person.id), class: :right do
    = icon 'pencil-square-o'
  .row
    .small-3.column
      span.th
        img src=userpic_src(person)
      .contact-data
        = email_link person
        = phone_link person
        = skype_link person
        = moikrug_link person
        = linkedin_link person
        = github_link person
        = stackoverflow_link person
        = vk_link person
        = twitter_link person
        = googleplus_link person
        = resume_link person
    .small-9.column
      h3 = person.name
      dl.tabs data-tab=""
        / dd.active
        /   a href="#panel-contacts-#{person.id}"  Контакты
        dd.active
          a href="#panel-skills-#{person.id}"  Скилы
        dd
          a href="#panel-experience-#{person.id}"  Опыт
      .tabs-content
        .content.active id="panel-skills-#{person.id}"
          p = raw(person.skills)
        .content id="panel-experience-#{person.id}"
          - (person.experience || []).each do |item|
            h5
              = "#{item[:title]} "
              small = item[:company]
            p = raw(item[:duties])
    .small-12.column
      - if person.new?
        = link_to accept_project_person_path(id: person.id), method: :put, class: [:button, :right, :small] do
          = icon 'thumbs-up'
        = link_to reject_project_person_path(id: person.id), method: :put, class: [:button, :small, :secondary] do
          = icon 'trash'
      - else
        a.button.right.small data-reveal-id="create-event" data-person-id=person.id href="#"
          = icon :comment

app/views/people/_skills.html.slim
.row
  .small-12.column
    label
      | Навыки
      = f.text_area :skills, rows: 12

app/views/people/index.html.slim
- content_for :active_tab do
  = form_for last_query, url: search_project_people_path, method: :post do |f|
    .row
      .small-12.column
        .row.collapse
          .small-10.column
            = f.text_field :specializations, placeholder: "Кейворды", value: last_query.specializations.join(", ")
            p.stuck-bottom
              | через зaпятую
              a.right href="#" data-behaviour='show-advanced-search' Расширенный поиск
          .small-2.column
            input.postfix type="submit" value="Искать!"
    #advanced-search.panel.callout
      .row
        .small-4.column
          label
            | В городе
            = f.text_field :city, placeholder: "Москва"
        .small-4.column
          label
            | За последние
            = f.text_field :period, placeholder: "2"
            p.stuck-bottom месяцa
        .small-4.column
          label Ищет работу
          = f.radio_button :contender, true
          label for="looking-for" Да
          = f.radio_button :contender, false
          label for="not-looking-for" Нет
    .row
      .small-12.column
        .panel.debug
          small
            = "moikrug_query: #{project.stats[:moikrug_last_query]}"
    - if persons.present?
      .row
        table data-selected-person="#{(person && person.id)}"
          tbody
            - persons.each_with_index do |person, i|
              = render 'person', person: person
              tr
                td.userpic
                  a.th data-reveal-id="show-person-#{person.id}" href="#"
                    img.userpic src=userpic_src(person)
                td
                  a data-reveal-id="show-person-#{person.id}" href="#"
                    = person.name
    - elsif params[:query].present?
      .row
        .small-12.column
          h1.text-center Никого нет!
    .row
      .small-12.column
        - next_page = project.stats[:pages_processed].to_i + 1
        input type=:hidden name=:page value=next_page
        - if persons.present? && last_query.specializations.present?
          input.button.expand.success type="submit" value="Еще!" name=:more
    .row
      .small-12.column
        a.button.tiny.right href='#' data-reveal-id="create-person"
          = "Добавить человечка"
        = link_to clear_project_people_path, method: :delete, class: [:button, :tiny, :right, :secondary] do
          = "Очистить песочницу"

= render 'events/create_event'

#create-person.reveal-modal data-reveal=''
  h2 Добавить человечка
  = form_for :person, url: project_people_path, method: :post do |f|
    .row
      .small-12.columns
        label
          | Имя
          = f.text_field :name
    .row
      .small-12.columns
        input.small.button.right type="submit" value="Сохранить"

app/views/people/show.html.slim
= form_for person, url: project_person_path, method: :patch do |f|
  .row
    .small-3.column
      span.th
        img src=userpic_src(person)
    .small-9.column
      h3 = person.name
    .small-9.column
      label
        | Имя
        = f.text_field :name
    .small-9.column
      dl.tabs data-tab=""
        dd.active
          a href="#panel-contacts"  Контакты
        dd
          a href="#panel-skills"  Скилы
        dd
          a href="#panel-experience"  Опыт
      .tabs-content
        .content.active id="panel-contacts"
          = render 'contacts', f: f
        .content id="panel-skills"
          = render 'skills', f: f
        .content id="panel-experience"
          = render 'experience', f: f
  .row
    .small-12.column
      input.button.small.right type=:submit value='Сохранить'