config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :projects do
    resource :project_interview, only: [:show, :update], path: :interview
    resource :project_questionnaire, only: [:show, :update], path: :questionnaire
    resources :project_templates, path: :templates do
      get :preview
    end

    resources :people, only: [:index, :create, :show, :update] do
      member do
        put :accept
        put :reject
      end

      collection do
        post :search
        delete :clear
      end
    end
  end

  resources :events

  resource :settings, only: [:show, :update] do
    resources :settings_templates, path: :templates
  end

  resources :word_relations

end

app/models/event.rb
class Event
  include Mongoid::Document
  include Mongoid::Timestamps
  extend EnumerateIt

  class Kind < EnumerateIt::Base
    associate_values :call, :email, :meeting
  end

  field :kind, type: String

  field :planned_at, type: DateTime
  field :closed_at, type: DateTime
  field :note, type: String

  belongs_to :person
  belongs_to :project
  belongs_to :owner, class_name: "User", inverse_of: :events
  embeds_many :interview, class_name: 'Question', as: :askable

  scope :of, -> (user) { where(owner: user) }
  scope :today, -> { gte(planned_at: Date.current) }
  scope :overdue, -> { where(closed_at: nil).lt(planned_at: Time.zone.now) }
  scope :next, -> { where(closed_at: nil).gte(planned_at: Date.tomorrow) }
  scope :someday, -> { where(closed_at: nil).gte(planned_at: Date.tomorrow + 1.day) }

  validates :kind, presence: true
  validates :owner, presence: true
  validates :planned_at, presence: true

  has_enumeration_for :kind, with: Kind, create_helpers: true

  def close!
    self.closed_at = Time.zone.now
  end

  def closed?
    closed_at.present?
  end

  def due?
    planned_at.to_date == Date.current
  end

  def overdue?
    planned_at < Time.zone.now
  end

  def actual_interview
    return interview if interview.present?
    project.interview.map { |question| Question.new(question: question) }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include Projectable

  layout 'dashboard'
  helper_method :projects, :event, :events, :persons

  def index
  end

  def show
  end

  def create
    create_event!
    close_parent!
    redirect_to :index
  end

  def update
    update_event!
    update_interview!
    redirect_to :show
  end

  def destroy
    event.delete
    redirect_to :index
  end

  private

  def event
    @event ||= events_collection.find(params[:id])
  end

  def events
    case focus
    when :today
      overdue_events + today_events
    when :next
      next_events
    when :someday
      someday_events
    else
      []
    end
  end

  def focus
    if params.key? :focus
      params.permit(:focus)[:focus].to_sym
    else
      :today
    end
  end

  def today_events
    @today_events ||= events_collection.today.order_by(closed_at: 1, planned_at: -1)
  end

  def overdue_events
    @overdue_events ||= events_collection.overdue.order_by(planned_at: -1)
  end

  def next_events
    @next_events ||= events_collection.next.order_by(planned_at: -1)
  end

  def someday_events
    @someday_events ||= events_collection.someday.order_by(planned_at: -1)
  end

  def events_collection
    Event.of(current_user)
  end

  def persons
    Person.of(current_user).accepted
  end

  def create_event!
    Event::Creator.new(current_user, new_event_params).call
  end

  def new_event_params
    params.require(:event).permit(:kind, :person, :planned_at, :note).merge!(planned_at: planned_at)
  end

  def update_event!
    event.update_attributes! event_params
  end

  def event_params
    params.require(:event).permit(:note).merge! planned_at: planned_at
  end

  def update_interview!
    event.interview = []
    interview_params[:interview].each do |item|
      event.interview << Question.new(item)
    end
    event.save!
  end

  def interview_params
    params.require(:event).permit(interview: [:question, :answer])
  end

  def close_parent!
    return unless parent_event
    parent_event.close!
    parent_event.save!
  end

  def parent_event
    return unless params[:parent_event].present?
    @parent_event ||= events_collection.find(params[:parent_event])
  end

  def planned_at
    p = params.require(:event).permit(:planned_at_date, :planned_at_time)
    DateTime.strptime("#{p[:planned_at_date]} #{p[:planned_at_time]}", '%d.%m.%Y %H:%M')
  end

  def index_url
    events_path
  end

  def show_url
    event_url event
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_icon event
    case event.kind
    when Event::Kind::CALL
      :phone
    when Event::Kind::EMAIL
      :envelope
    when Event::Kind::MEETING
      :users
    else
      :glass
    end
  end

  def event_classes event
    case
    when event.closed?
      :closed
    when event.due?
      :due
    when event.overdue?
      :overdue
    else
      ''
    end
  end
end

app/views/events/_compose_tab.html.slim
.row
  .small-12.column
    select data-behaviour='select-template'
      option value='' = '(выбери шаблон)'
      - event.project.templates.each do |template|
        - url = project_project_template_preview_path(event.project, template)
        option value="#{url}?person_id=#{event.person_id}"
          = template.name
.row
  .small-12.column
    dl.tabs data-tab=""
      dd.active
        a href="#panel-formatted"  Красиво
      dd
        a href="#panel-html"  HTML
      dd
        a href="#panel-raw"  Разметка
    .tabs-content
      #panel-formatted.content.active
        #preview
          i some text will be here
      #panel-html.content
        textarea#preview-html rows=15
          | some text will be here
      #panel-raw.content
        textarea#preview-raw rows=15
          | some text will be here
.row
  .small-12.column
    a.button.tiny href='#'
      = icon 'paper-plane-o'

app/views/events/_create_event.html.slim
#create-event.reveal-modal data-reveal=''
  h2 Планируем новое событие
  = form_for :event, url: events_path do |f|
    input#parentEvent name=:parent_event type=:hidden
    .row
      .small-4.columns
        label
          | Что это будет
          = f.select :kind, Event::Kind.to_a
        label
          | С кем
          = f.collection_select :person, persons, :id, :name, include_blank: true
        label
          | Когда
          .datetime-selector
            .row
              .small-8.column
                input.date-input type=:text name='event[planned_at_date]' placeholder='дд.мм.гггг'
              .small-4.column
                input.time-input type=:text name='event[planned_at_time]' placeholder='ЧЧ:ММ'
            .row
              .small-12.column
                a href='#' data-date=d(now) data-time=t(now) Сейчас
                a href='#' data-date=d(now + 1.hour) data-time=t(now + 1.hour) Через час
                a href='#' data-date=d(now + 1.day) data-time=t(now + 1.day) Завтра
      .small-8.columns
        label
          | Коммент
          textarea placeholder="так чтобы потом вспомнить о чем речь" name="event[note]" rows=10
      .small-12.columns
        input.small.button.right type="submit" value="Сохранить"
  a.close-reveal-modal ×

app/views/events/_event_tab.html.slim
.row
  .small-4.columns
    label
      | Когда
      .datetime-selector
        .row
          .small-8.column
            input.date-input type=:text name='event[planned_at_date]' placeholder='дд.мм.гггг' value=d(event.planned_at)
          .small-4.column
            input.time-input type=:text name='event[planned_at_time]' placeholder='ЧЧ:ММ' value=t(event.planned_at)
        .row
          .small-12.column
            a href='#' data-date=d(now) data-time=t(now) Сейчас
            a href='#' data-date=d(now + 1.hour) data-time=t(now + 1.hour) Через час
            a href='#' data-date=d(now + 1.day) data-time=t(now + 1.day) Завтра
  .small-8.columns
    label
      | Коммент
      textarea placeholder="так чтобы потом вспомнить о чем речь" name="event[note]" rows=10
        = event.note

app/views/events/_interview_tab.html.slim
.row
  .small-12.column
    = render 'questions/questions', collection: event.actual_interview, key: 'event[interview]'

app/views/events/index.html.slim
- content_for :payload
  .row
    .small-12.column
      dl.sub-nav
        dd.active
          a.left data-reveal-id="create-event" href="#" = icon :plus
        dt
          | |
        dd
          a href='#' = icon :phone
        dd
          a href='#' = icon :envelope
  .row
    .small-12.column
      table
        tboby
          - events.each do |event|
            tr class=event_classes(event)
              td width=30 = icon event_icon(event)
              td width=70
                .right
                  = event.planned_at.strftime '%H:%M'
                  br
                  small
                    = event.planned_at.strftime '%d.%m.%Y'
              td
                = link_to event_path(event) do
                  = event.person.try :name
                br
                small
                  = event.note

= render 'create_event'

app/views/events/show.html.slim
= content_for :payload
  .row
    .small-12.column
      h2
        = icon event_icon(event)
        = " #{event.person.name}"
      = form_for event do |f|
        dl.tabs data-tab=""
          dd.active
            a href="#panel-event"  Событие
          dd
            a href="#panel-interview"  Интервью
          dd
            a href="#panel-compose"  Написать
        .tabs-content
          #panel-event.content.active
            = render 'event_tab', event: event
          #panel-interview.content
            = render 'interview_tab', event: event
          #panel-compose.content
            = render 'compose_tab', event: event
        .row
          .small-12.columns.right
            input.small.button.right type="submit" value="Сохранить"
            = link_to event_path(event), method: :delete, class: [:small, :button, :secondary, :left] do
              = icon :trash
            a.small.button.secondary.left data-reveal-id="create-event" data={ person_id: event.person.id,
                                                                              parent_event: event.id } href="#"
              | Готово!

  = render 'create_event'