config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :projects do
    resource :project_interview, only: [:show, :update], path: :interview
    resource :project_questionnaire, only: [:show, :update], path: :questionnaire
    resources :project_templates, path: :templates do
      get :preview
    end

    resources :people, only: [:index, :create, :show, :update] do
      member do
        put :accept
        put :reject
      end

      collection do
        post :search
        delete :clear
      end
    end
  end

  resources :events

  resource :settings, only: [:show, :update] do
    resources :settings_templates, path: :templates
  end

  resources :word_relations

end

app/models/settings.rb
class Settings
  include Mongoid::Document

  field :questionnaire, type: Array, default: ->{ [] }
  field :interview, type: Array, default: ->{ [] }

  embeds_many :templates, class_name: "Template", as: :templatable
  embedded_in :user
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  helper_method :settings

  def show
  end

  def update
    user.settings.questionnaire = questionnaire if params.has_key?(:questionnaire)
    user.settings.interview = interview if params.has_key?(:interview)
    user.save!
    render action: :show
  end

  private

  def user
    @user ||= current_user
  end

  def settings
    user.settings ||= Settings.new
  end

  def questionnaire
    permitted[:questionnaire].select(&:present?)
  end

  def interview
    permitted[:interview].select(&:present?)
  end

  def permitted
    params.permit(questionnaire: [], interview: [])
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
  def active tab
    :active if params.has_key? tab
  end
end

app/views/settings/_interview.html.slim
.row
  .small-12.column
    .question-answer
      .rows.sortable
        - if settings.interview.empty?
          .row
            .small-12.columns
              input type=:text name="interview[]"
        - settings.interview.each do |question|
          .row
            .row.collapse.postfix-radius
              .small-11.columns
                input type=:text value=question name="interview[]"
              .small-1.columns
                span.postfix
                  = icon :bars
      .row
        .small-12.columns
          a.tiny.button data-behaviour="new-question" href="#" +
          input.small.button.right type="submit" value="Сохранить"

app/views/settings/_questionnaire.html.slim
.row
  .small-12.column
    .question-answer
      .rows.sortable
        - if settings.questionnaire.empty?
          .row
            .small-12.columns
              input type=:text name="questionnaire[]"
        - settings.questionnaire.each do |question|
          .row
            .row.collapse.postfix-radius
              .small-11.columns
                input type=:text value=question name="questionnaire[]"
              .small-1.columns
                span.postfix
                  = icon :bars
      .row
        .small-12.columns
          a.tiny.button data-behaviour="new-question" href="#" +
          input.small.button.right type="submit" value="Сохранить"

app/views/settings/show.html.slim
.row
  .small-12.column
    h1 Настройки
.row
  .small-12.column
      dl.sub-nav
        dd class=active(:questionnaire)
          a href="#{settings_path}?questionnaire"  Вопросы анкеты
        dd class=active(:interview)
          a href="#{settings_path}?interview"  План интервью
        dd
          a href=settings_settings_templates_path  Шаблоны
      .tabs-content
        #panel-questionnaire.content class=active(:questionnaire)
          = form_for :settings, url: settings_path, method: :put
            = render 'questionnaire'
        #panel-interview.content class=active(:interview)
          = form_for :settings, url: settings_path, method: :put
            = render 'interview'