config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :projects do
    resource :project_interview, only: [:show, :update], path: :interview
    resource :project_questionnaire, only: [:show, :update], path: :questionnaire
    resources :project_templates, path: :templates do
      get :preview
    end

    resources :people, only: [:index, :create, :show, :update] do
      member do
        put :accept
        put :reject
      end

      collection do
        post :search
        delete :clear
      end
    end
  end

  resources :events

  resource :settings, only: [:show, :update] do
    resources :settings_templates, path: :templates
  end

  resources :word_relations

end

app/controllers/project_templates_controller.rb
class ProjectTemplatesController < ApplicationController
  include Projectable

  helper_method :template, :rendered_body

  def index
  end

  def show
  end

  def create
    project.templates << Template.new(permitted)
    redirect_to :index
  end

  def update
    template.update permitted
    redirect_to :index
  end

  def destroy
    template.delete
    redirect_to :index
  end

  def preview
  end

  private

  def rendered_body
    person = Person.of(current_user).find(params[:person_id])
    Template::Renderer.new(template, person: person, project: project).call
  end

  def template
    project.templates.find template_id
  end

  def template_id
    params[:id] || params[:project_template_id]
  end

  def permitted
    params.require(:template).permit(:name, :private, :body)
  end

  def index_url
    project_project_templates_url
  end
end

app/helpers/project_templates_helper.rb
module ProjectTemplatesHelper
  def template_path template
    project_project_template_path(template)
  end
end

app/views/project_templates/index.html.slim
- content_for :active_tab do
  .row
    .small-12.column
      = render 'templates/grid', templates: project.templates
  .row
    .small-12.column
      a.tiny.button data-reveal-id="create-template" href="#"
        = icon :plus

= render 'templates/create_template', url: project_project_templates_path

app/views/project_templates/show.html.slim
- content_for :active_tab do
  .row
    .small-12.column
      = render 'templates/form', url: project_project_template_path(id: template)